config/routes.rb
Jpt::Application.routes.draw do
  resources :setsubis do
    collection {post :import}
    collection {get :export_csv}
  end
  get 'kanris/index'

  get 'kanri/index'

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanyokenmsts do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :tsushinseigyous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonyoukens do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonkaitous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengons do
    collection {get :export_csv}
  end


  root to: 'main#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :bashokubunmsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :bunruis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :shoninshamsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :ekis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kikanmsts do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_basho, :create_kaisha, :time_line_view}
    collection {get :time_line_view}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :shainmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end


  resources :jpt_holiday_msts do
    collection {post :ajax, :import}
    collection{get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	match 'main', to: 'main#index', via: [:get]

  resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :import}
  end

  resources :yakushokumasters, param: :id do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search}
    collection {get :shonin_search}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :shozokumasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kaishamasters, param: :id do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection {post :ajax}
      collection{post :import}
      collection {get :export_csv}
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end
end

app/models/kikanmst.rb
class Kikanmst < ActiveRecord::Base
  self.table_name = :機関マスタ
  self.primary_key = :機関コード

  validates :機関コード, :機関名, presence: true
  validates :機関コード, uniqueness: true

  alias_attribute :id, :機関コード
  alias_attribute :name, :機関名
  alias_attribute :note, :備考

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Kikanmst.create! row.to_hash
    end
  end

  def self.to_csv
    attributes = %w{機関コード 機関名 備考}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |kikanmst|
        csv << attributes.map{ |attr| kikanmst.send(attr) }
      end
    end
  end
end

app/controllers/kikanmsts_controller.rb
class KikanmstsController < ApplicationController
  before_action :require_user!
  before_action :set_kikanmst, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: :export_csv

  respond_to :html

  def index
    @kikanmsts = Kikanmst.all
    respond_with(@kikanmsts)
  end

  def show
    respond_with(@kikanmst)
  end

  def new
    @kikanmst = Kikanmst.new
    respond_with(@kikanmst)
  end

  def edit
  end

  def create
    @kikanmst = Kikanmst.new(kikanmst_params)
    @kikanmst.save
    respond_with(@kikanmst)
  end

  def update
    @kikanmst.update(kikanmst_params)
    respond_with(@kikanmst)
  end

  def destroy
    @kikanmst.destroy
    respond_with(@kikanmst)
  end

  def import
    if params[:file].nil?
      flash[:alert] = t "app.flash.file_nil"
      redirect_to kikanmsts_path
    elsif File.extname(params[:file].original_filename) != ".csv"
      flash[:danger] = t "app.flash.file_format_invalid"
      redirect_to kikanmsts_path
    else
      begin
        Kikanmst.transaction do
          Kikanmst.delete_all
          Kikanmst.reset_pk_sequence
          Kikanmst.import(params[:file])
          notice = t 'app.flash.import_csv'
          redirect_to :back, notice: notice
        end
      rescue => err
        flash[:danger] = err.to_s
        redirect_to kikanmsts_path
      end
    end
  end

  def export_csv
    @kikanmsts = Kikanmst.all

    respond_to do |format|
      format.html
      format.csv { send_data @kikanmsts.to_csv, filename: "機関マスタ.csv" }
    end
  end

  private
    def set_kikanmst
      @kikanmst = Kikanmst.find(params[:id])
    end

    def kikanmst_params
      params.require(:kikanmst).permit(:機関コード, :機関名, :備考 )
    end
end

app/helpers/kikanmsts_helper.rb
module KikanmstsHelper
end

app/views/kikanmsts/_form.html.haml
= simple_form_for @kikanmst do |f|
  .col-sm-3.col-sm-offset-3
    = f.input :機関コード if mode == :new
    = f.input :機関名
    = f.input :備考
    = f.button :submit, class: 'btn btn-primary'

app/views/kikanmsts/edit.html.haml
%ol.breadcrumb
  %li= link_to 'メニュー', main_path
  %li= link_to '機関一覧', kikanmsts_path
  %li.active 編集

= render 'form', mode: :edit

app/views/kikanmsts/index.html.haml
= javascript_include_tag 'kikanmsts'

%ol.breadcrumb
  %li= link_to 'メニュー', main_path
  %li.active 機関

%table.kikantable.table.table-striped.table-bordered.table-hover{cellspacing:0, width: '100%'}
  %thead
    %tr
      %th 機関コード
      %th 機関名
      %th 備考
      %th
      %th

  %tbody
    - @kikanmsts.each do |kikanmst|
      %tr
        %td= kikanmst.機関コード
        %td= kikanmst.機関名
        %td= kikanmst.備考
        %td= link_to '編集', edit_kikanmst_path(kikanmst)
        - msg = t 'app.delete_confirm'
        %td= link_to '削除', kikanmst, :method => :delete, :data => { :confirm => msg }

%br

= link_to '新規', new_kikanmst_path

- if can? :update, @kikanmsts
  %h4 CSVでのデータをインポート!
  = form_tag import_kikanmsts_path,class:'form-inline', multipart: true do
    .form-group
      = label_tag 'selectcsv', nil, class: 'sr-only'
      = file_field_tag :file , class: 'btn btn-default'
    .form-group
      = label_tag 'importcsv', nil, class: 'sr-only'
      = submit_tag "Import CSV" , class: 'btn btn-default'

app/views/kikanmsts/new.html.haml
%ol.breadcrumb
  %li= link_to 'メニュー', main_path
  %li= link_to '機関一覧', kikanmsts_path
  %li.active 新規


= render 'form', mode: :new

app/views/kikanmsts/show.html.haml
%p
  %b 機関コード:
  = @kikanmst.機関コード
%p
  %b 機関名:
  = @kikanmst.機関名
%p
  %b 備考:
  = @kikanmst.備考

= link_to '編集', edit_kikanmst_path(@kikanmst)
\|
= link_to '戻る', kikanmsts_path