config/routes.rb
Jpt::Application.routes.draw do
  resources :setsubis do
    collection {post :import}
    collection {get :export_csv}
  end
  get 'kanris/index'

  get 'kanri/index'

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanyokenmsts do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :tsushinseigyous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonyoukens do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonkaitous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengons do
    collection {get :export_csv}
  end


  root to: 'main#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :bashokubunmsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :bunruis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :shoninshamsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :ekis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kikanmsts do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_basho, :create_kaisha, :time_line_view}
    collection {get :time_line_view}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :shainmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end


  resources :jpt_holiday_msts do
    collection {post :ajax, :import}
    collection{get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	match 'main', to: 'main#index', via: [:get]

  resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :import}
  end

  resources :yakushokumasters, param: :id do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search}
    collection {get :shonin_search}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :shozokumasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kaishamasters, param: :id do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection {post :ajax}
      collection{post :import}
      collection {get :export_csv}
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end
end

app/controllers/export_csv_controller.rb
class ExportCsvController < ApplicationController
  before_action :require_user!
  before_action :check_user, only: :index
  def index
  end

  private
  def check_user
    redirect_to root_path if !current_user.admin? && !current_user.supervisor?
  end
end

app/views/export_csv/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">データをエクスポート</li>
</ol>

<% @index = 0 %>
<table id="export_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>STT</th>
      <th>ダウンロード</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "担当者マスタ", export_csv_users_path(format: :csv) %></td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "Jobマスタ", export_csv_jobmasters_path(format: :csv) %></td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "経費ヘッド", export_csv_keihiheads_path(format: :csv) %></td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "経費ボディ", export_csv_keihibodies_path(format: :csv) %></td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "イベントマスタ", export_csv_events_path(format: :csv) %></td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "ジュピター休日",
        export_csv_jpt_holiday_msts_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "勤怠",
        export_csv_kintais_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "会社マスタ",
        export_csv_kaishamasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "伝言",
        export_csv_dengons_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "伝言回答マスタ",
        export_csv_dengonkaitous_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "伝言用件マスタ",
        export_csv_dengonyoukens_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "分類マスタ",
        export_csv_bunruis_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "回覧",
        export_csv_kairans_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "回覧詳細",
        export_csv_kairanshosais_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "回覧用件マスタ",
        export_csv_kairanyokenmsts_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "場所マスタ",
        export_csv_bashomasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "場所区分マスタ",
        export_csv_bashokubunmsts_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "工程マスタ",
        export_csv_kouteimasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "役職マスタ",
        export_csv_yakushokumasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "所在マスタ",
        export_csv_shozais_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "所属マスタ",
        export_csv_shozokumasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "承認者マスタ",
        export_csv_shoninshamsts_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "機関マスタ",
        export_csv_kikanmsts_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "状態マスタ",
        export_csv_joutaimasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "社員マスタ",
        export_csv_shainmasters_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "通信制御マスタ",
        export_csv_tsushinseigyous_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "駅マスタ",
        export_csv_ekis_path(format: :csv) %>
      </td>
    </tr>
    <tr>
      <td><%= @index+=1 %></td>
      <td><%= link_to "設備マスタ",
        export_csv_setsubis_path(format: :csv) %>
      </td>
    </tr>
  </tbody>
</table>