config/routes.rb
Jpt::Application.routes.draw do
  resources :setsubis do
    collection {post :import}
    collection {get :export_csv}
  end
  get 'kanris/index'

  get 'kanri/index'

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanyokenmsts do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :tsushinseigyous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonyoukens do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonkaitous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengons do
    collection {get :export_csv}
  end


  root to: 'main#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :bashokubunmsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :bunruis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :shoninshamsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :ekis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kikanmsts do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_basho, :create_kaisha, :time_line_view}
    collection {get :time_line_view}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :shainmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end


  resources :jpt_holiday_msts do
    collection {post :ajax, :import}
    collection{get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	match 'main', to: 'main#index', via: [:get]

  resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :import}
  end

  resources :yakushokumasters, param: :id do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search}
    collection {get :shonin_search}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :shozokumasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kaishamasters, param: :id do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection {post :ajax}
      collection{post :import}
      collection {get :export_csv}
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end
end

app/models/shozokumaster.rb
class Shozokumaster < ActiveRecord::Base
  self.table_name = :所属マスタ
  self.primary_key = :所属コード

  validates :所属コード, :所属名, presence: true
  validates :所属コード, uniqueness: true

  has_many :kouteimasters, foreign_key: :所属コード
  has_one :shainmaster, foreign_key: :所属コード

  alias_attribute :id, :所属コード
  alias_attribute :name, :所属名

  # a class method import, with file passed through as an argument
  def self.import(file)
    # a block that runs through a loop in our CSV data
    CSV.foreach(file.path, headers: true) do |row|
      # creates a user for each row in the CSV file
      Shozokumaster.create! row.to_hash
    end
  end

  def self.to_csv
    attributes = %w{所属コード 所属名}

    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |shozokumaster|
        csv << attributes.map{ |attr| shozokumaster.send(attr) }
      end
    end
  end
end

app/controllers/shozokumasters_controller.rb
class ShozokumastersController < ApplicationController
  before_action :require_user!
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource except: :export_csv
  respond_to :js

  def index
  end

  def show
  end

  def new
  end

  def edit

  end

  def create
    flash[:notice] = t "app.flash.new_success" if @shozokumaster.save
    respond_with @shozokumaster

  end

  def update
    flash[:notice] = t "app.flash.update_success" if @shozokumaster.
      update_attributes shozokumaster_params
    respond_with @shozokumaster
  end

  def destroy
    @shozokumaster.destroy
    respond_with @shozokumaster, location: shozokumasters_url
  end

  def import
    if params[:file].nil?
      flash[:alert] = t "app.flash.file_nil"
      redirect_to shozokumasters_path
    elsif File.extname(params[:file].original_filename) != ".csv"
      flash[:danger] = t "app.flash.file_format_invalid"
      redirect_to shozokumasters_path
    else
      begin
        Shozokumaster.transaction do
          Shozokumaster.delete_all
          Shozokumaster.reset_pk_sequence
          Shozokumaster.import(params[:file])
          notice = t 'app.flash.import_csv'
          redirect_to :back, notice: notice
        end
      rescue => err
        flash[:danger] = err.to_s
        redirect_to shozokumasters_path
      end
    end
  end

  def export_csv
    @shozokumasters = Shozokumaster.all

    respond_to do |format|
      format.html
      format.csv { send_data @shozokumasters.to_csv, filename: "所属マスタ.csv" }
    end
  end

  private
  def shozokumaster_params
    params.require(:shozokumaster).permit :所属コード, :所属名
  end
end

app/views/shozokumasters/_form.html.haml
= simple_form_for @shozokumaster do |f|
  .col-sm-3.col-sm-offset-3
    = f.input :所属コード if mode == :new
    = f.input :所属名
    = f.button :submit, class: 'btn btn-primary'

app/views/shozokumasters/destroy.js.erb
// remove from selected id
$('#shozokumaster_<%= @shozokumaster.id %>').remove();

app/views/shozokumasters/edit.html.erb
<%= javascript_include_tag 'shain' %>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li><%= link_to '所属マスタ', shozokumasters_path %></li>
  <li class="active">編集</li>
</ol>

<%= render 'form', mode: :edit  %>

app/views/shozokumasters/index.html.erb
<%= javascript_include_tag 'shozoku' %>

<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">所属マスタ</li>
</ol>

<!-- <h1>工程マスタ</h1> -->

<table id="shozokumaster" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">

  <thead>
  <tr>
    <th>所属コード</th>
    <th>所属名</th>
    <th colspan="2">アクション</th>
  </tr>
  </thead>

  <tbody>
  <% @shozokumasters.each do |shozoku| %>
      <tr id="shozokumaster_<%= shozoku.id %>">
      <td><%= shozoku.所属コード %></td>
        <td><%= shozoku.所属名 %></td>
        <td><%= link_to '編集', edit_shozokumaster_path(shozoku) if
          current_user.admin? %></td>
        <td><%= link_to '削除', shozoku, method: :delete, data: {confirm:
          '削除で宜しですか。'} if current_user.admin? %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to '新規', new_shozokumaster_path if current_user.admin? %>

<% if current_user.admin? %>
  <h4>CSVでのデータをインポート!</h4>
  <%= form_tag import_shozokumasters_path, class:'form-inline',
    multipart: true do %>
    <div class="form-group">
      <%= label_tag 'selectcsv', nil, class: 'sr-only' %>
      <%= file_field_tag :file , class: 'btn btn-default',
        accept: 'text/csv' %>
    </div>
    <div class="form-group">
      <%= label_tag 'importcsv', nil, class: 'sr-only' %>
      <%= submit_tag "Import CSV" , class: 'btn btn-default' %>
    </div>
  <% end %>
<% end %>

app/views/shozokumasters/new.html.erb
<%= javascript_include_tag 'shozoku' %>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li><%= link_to '所属マスタ', shozokumasters_path %></li>
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">新規</li>
</ol>

<!-- <h1>工程マスタ・新規入力</h1> -->

<%= render 'form', mode: :new %>

app/views/shozokumasters/show.html.erb
<p>
  <strong>所属コード:</strong>
  <%= @shozokumaster.所属コード %>
</p>

<p>
  <strong>所属名:</strong>
  <%= @shozokumaster.所属名 %>
</p>

<%= link_to '編集', edit_shozokumaster_path(@shozokumaster) %> |
<%= link_to '戻る', shozokumasters_path %>