config/routes.rb
Jpt::Application.routes.draw do
  resources :setsubis do
    collection {post :import}
    collection {get :export_csv}
  end
  get 'kanris/index'

  get 'kanri/index'

  resources :kairans do
    collection {post :confirm, :kaitou_create}
    collection {get :shokairan}
    member {get :kaitou, :send_kairan_view}
    collection {get :export_csv}
  end

  resources :kairanyokenmsts do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :kairanshosais do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :tsushinseigyous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonyoukens do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengonkaitous do
    collection {get :export_csv}
    collection {post :import}
  end

  resources :dengons do
    collection {get :export_csv}
  end


  root to: 'main#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :bashokubunmsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :bunruis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :shoninshamsts  do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :ekis do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kikanmsts do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kintais do
    collection {get :search}
    collection {get :export_csv}
  end

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection {post :ajax, :custom, :create_basho, :create_kaisha, :time_line_view}
    collection {get :time_line_view}
    collection {get :export_csv}
	end

  resources :bashomasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :shainmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end


  resources :jpt_holiday_msts do
    collection {post :ajax, :import}
    collection{get :export_csv}
  end

  resources :jobmasters do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

	match 'main', to: 'main#index', via: [:get]

  resources :users do
    collection {get :change_pass}
    collection {post :change_pass}
    collection {get :export_csv}
    collection {post :import}
  end

  resources :yakushokumasters, param: :id do
    collection {post :ajax, :import}
    collection {get :export_csv}
  end

  resources :keihiheads do
    collection {post :ajax, :shonin_search}
    collection {get :shonin_search}
    collection {get :export_csv}
  end

  resources :keihibodies do
    collection {get :export_csv}
  end

  resources :shozokumasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :joutaimasters do
    collection {post :import}
    collection {get :export_csv}
  end

  resources :kaishamasters, param: :id do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :shozais do
    collection { post :import}
    collection {get :export_csv}
  end

  resources :setsubiyoyakus do
  end

  constraints(:id => /\w+(,\w+)*/) do
    resources :kouteimasters do
      collection {post :ajax}
      collection{post :import}
      collection {get :export_csv}
    end
  end

  resources :export_csv, only: :index

  namespace :kanris do
    root to: "main#index"
    resources :kintais, only: [:index, :show] do
      collection {get :export_excel}
    end
    resources :keihiheads, only: :index
  end
end

app/models/dengon.rb
class Dengon < ActiveRecord::Base
  self.table_name = :伝言

  belongs_to :input_user, foreign_key: :入力者, class_name: 'Shainmaster'
  belongs_to :to_user, foreign_key: :社員番号, class_name: 'Shainmaster'
  belongs_to :dengonyouken, foreign_key: :用件, class_name: 'Dengonyouken'
  belongs_to :dengonkaitou, foreign_key: :回答, class_name: 'Dengonkaitou'

  delegate :氏名, to: :input_user, prefix: :input_user, allow_nil: true
  delegate :氏名, to: :to_user, prefix: :to_user, allow_nil: true
  delegate :種類名, to: :dengonyouken, prefix: :youken, allow_nil: true
  delegate :種類名, to: :dengonkaitou, prefix: :kaitou, allow_nil: true

  def self.to_csv
    attributes = %w{id from1 from2 日付 入力者 用件 回答 伝言内容 確認 送信 社員番号}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |dengon|
        csv << attributes.map{ |attr| dengon.send(attr) }
      end
    end
  end
end

app/controllers/dengons_controller.rb
class DengonsController < ApplicationController
  before_action :require_user!
  before_action :set_dengon, only: [:show, :edit, :update, :destroy]

  respond_to :html
  include DengonsHelper

  def index
    @dengons = Dengon.all
    if params[:head].present?
      @shain_param = params[:head][:shainbango]
    else
      @shain_param = session[:user]
    end
    @yoken = params[:head][:youken] if params[:head].present?
    @kaitou = params[:head][:kaitou] if params[:head].present?

    @dengons = @dengons.where("社員番号 = ? or 入力者 = ?", @shain_param, @shain_param) if @shain_param.present?
    @dengons = @dengons.where(用件: @yoken) if @yoken.present?
    @dengons = @dengons.where(回答: @kaitou) if @kaitou.present?
    respond_with(@dengons)
  end

  def show
    respond_with(@dengon)
  end

  def new
    @dengon = Dengon.new
    @dengon.input_user = Shainmaster.find session[:user]
    respond_with(@dengon)
  end

  def edit
  end

  def create
    @dengon = Dengon.new(dengon_params)
    @dengon.save
    # respond_with(@dengon)
    update_dengon_counter dengon_params
    # mail_to = Tsushinseigyou.find_by!(社員番号: dengon_params[:社員番号]).メール;
    # send_mail(mail_to, dengon_params[:回答], dengon_params[:伝言内容])

  rescue ActiveRecord::RecordNotFound
    flash[:notice] = t "app.flash.mail_to"
  rescue Net::SMTPFatalError
    flash[:notice] = t "app.flash.mail_send_field"
  ensure
    redirect_to dengons_url
  end

  def update
    @dengon.update(dengon_params)
    # respond_with(@dengon)
    update_dengon_counter dengon_params
    # mail_to = Tsushinseigyou.find_by!(社員番号: dengon_params[:社員番号]).メール;
    # send_mail(mail_to, dengon_params[:回答], dengon_params[:伝言内容])

  rescue ActiveRecord::RecordNotFound
    flash[:notice] = t "app.flash.mail_to"
  rescue Net::SMTPFatalError
    flash[:notice] = t "app.flash.mail_send_field"
  ensure
    redirect_to dengons_url
  end

  def destroy
    @dengon.destroy
    respond_with(@dengon)
  end

  def export_csv
    @dengons = Dengon.all

    respond_to do |format|
      format.html
      format.csv { send_data @dengons.to_csv, filename: "伝言.csv" }
    end
  end

  private
    def set_dengon
      @dengon = Dengon.find(params[:id])
    end

    def dengon_params
      params.require(:dengon).permit(:from1, :from2, :日付, :入力者, :社員番号, :用件, :回答, :伝言内容, :確認, :送信)
    end
end

app/helpers/dengons_helper.rb
module DengonsHelper
  def update_dengon_counter dengon_params
    counter = Dengon.where(社員番号: dengon_params[:社員番号], 確認: false).count
    Shainmaster.find(dengon_params[:社員番号]).update(伝言件数: counter)
  end

  def send_mail(to_mail, subject_mail, body_mail)
    Mail.deliver do
      to to_mail
      from 'hminhduc@gmail.com'
      subject subject_mail
      body body_mail
    end
  end
end

app/views/dengons/_form.html.haml
= simple_form_for(@dengon) do |f|
  = f.error_notification
  .col-md-3.col-md-offset-2
    = f.input :from1, label: '相手先'
    = f.input :from2, label: '名前'
    = f.input :日付, as: :date_time_picker
    = f.association :input_user, label_method: :氏名, value_method: :社員番号, label:'入力者'
    = f.association :to_user, label_method: :氏名, value_method: :社員番号, label:'社員'
    = f.association :dengonyouken, label_method: :種類名, value_method: :id, label:'用件'
    = f.association :dengonkaitou, label_method: :種類名, value_method: :id, label:'回答'
  .col-md-3.col-md-offset-1
    = f.input :伝言内容, as: :text
    = f.input :確認
    = f.input :送信

    = f.button :submit, class:'btn btn-primary'

app/views/dengons/_header.html.haml
.row-fruid
  .form-inline
    .form-group
      = label_tag :社員
      = select(:head, :shainbango, Shainmaster.all.collect {|p| [ p.氏名, p.社員番号 ] }, {selected: @shain_param, include_blank: true }, class: 'form-control')
    .form-group
      = label_tag :要件
      = select(:head, :youken, Dengonyouken.all.collect {|p| [ p.種類名, p.id ] }, {selected: @yoken, include_blank: true }, class: 'form-control')
    .form-group
      = label_tag :回答
      = select(:head, :kaitou, Dengonkaitou.all.collect {|p| [ p.種類名, p.id ] }, {selected: @kaitou, include_blank: true }, class: 'form-control')
    .pull-right
      = button_tag '検索する', class:'btn btn-primary'

app/views/dengons/edit.html.haml
= javascript_include_tag 'dengons'

%ol.breadcrumb
  %li= link_to 'メニュー', main_path
  %li= link_to '伝言一覧', dengons_path
  %li.active 編集

= render 'form'

app/views/dengons/index.html.haml
= javascript_include_tag 'dengons'

%ol.breadcrumb
  %li= link_to 'メニュー', main_path
  %li.active 伝言一覧

-#.row
  -#.col-md-5.col-md-offset-4
    -#%h2
      -#= "#{Time.now.strftime('%F %H:%M %A')}"
      -#= "#{Time.current.in_time_zone('').strftime('%F %H:%M %A')}"
      -#= "#{Date.current.in_time_zone.strftime('%F %H:%M %A')}"
%br

= form_for :dengon, url: dengons_path, html: {class:'form-inline'}, method: :get do |f|
  = render 'header', f:f
  %br
  %table.dengon.table.table-striped.table-bordered.table-hover{cellspacing: 0, width: '100%' }
    %thead
      %tr
        %th 相手先
        %th 名前
        %th 日付
        %th 入力者
        %th 社員
        %th 用件
        %th 回答
        %th 伝言内容
        %th 確認
        %th 送信
        %th
        %th

    %tbody
      - @dengons.each do |dengon|
        %tr
          %td= dengon.from1
          %td= dengon.from2
          %td= dengon.日付.strftime("%F %H:%M") if dengon.日付
          %td= dengon.input_user_氏名
          %td= dengon.to_user_氏名
          %td= dengon.youken_種類名
          %td= dengon.kaitou_種類名
          %td= dengon.伝言内容
          -#%td{'word-wrap' => 'break-word'}= dengon.伝言内容
          %td= dengon.確認 == true ? '確認済':'未確認'
          %td= dengon.送信 == true ? '許可':'不可'
          %td= link_to '編集', edit_dengon_path(dengon)
          %td= link_to '削除', dengon, :method => :delete, :data => { :confirm => '削除で宜しいですか。' }

%br

= link_to '新規', new_dengon_path

app/views/dengons/new.html.haml
= javascript_include_tag 'dengons'

%ol.breadcrumb
  %li= link_to 'メニュー', main_path
  %li= link_to '伝言一覧', dengons_path
  %li.active 新規

= render 'form'

app/views/dengons/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @dengon.first_name
%p
  %b Last name:
  = @dengon.last_name

= link_to 'Edit', edit_dengon_path(@dengon)
\|
= link_to 'Back', dengons_path